name: Create Workflow Data JSON

on:
  push:
    branches:
      - master

jobs:
  create-json:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create JSON file with workflow data
        run: |
          echo "{
            \"event_name\": \"${{ github.event_name }}\",
            \"workflow\": \"${{ github.workflow }}\",
            \"run_id\": \"${{ github.run_id }}\",
            \"run_number\": \"${{ github.run_number }}\",
            \"commit\": \"${{ github.sha }}\",
            \"repository\": \"${{ github.repository }}\",
            \"actor\": \"${{ github.actor }}\",
            \"ref\": \"${{ github.ref }}\",
            \"event_time\": \"${{ github.event.head_commit.timestamp }}\"
          }" > workflow_data.json

      - name: Upload workflow data file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: workflow-data
          path: workflow_data.json
    
  generate-report:
      needs: create-json
      runs-on: ubuntu-latest
      steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Download audit report artifact
        uses: actions/download-artifact@v4
        with:
          name: workflow_data.json
          path: .
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Read and output JSON in tabular format
        run: |
          JSON_FILE="workflow_data.json"
          jq -r '[
            "Event Name", "Workflow", "Run ID", "Run Number", "Commit", "Repository", "Actor", "Ref", "Event Time",
            "\(.event_name)", "\(.workflow)", "\(.run_id)", "\(.run_number)", "\(.commit)", "\(.repository)", "\(.actor)", "\(.ref)", "\(.event_time)"
          ] | @tsv' $JSON_FILE